### ISSUE TITLE
Missing background_probs_wgs.rds

### ISSUE THREAD

**Issue by xtmgah** [TomasettiLab/supersigs#10]
Hello:

Thanks for developing this useful tool for mutational signature analysis. Very interesing. 
Can you include the 'background_probs_wgs.rds' to the github? I am trying to run your algorithm using our WGS dataset but the 'background_probs_wgs.rds' file was missing from the GitHub.  Thanks

**Comment by albertkuo** [comment]
Added background_probs_wgs
